//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ma5zeny
{
    using System;
    using System.Collections.Generic;
    
    public partial class Buying_Invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Buying_Invoice()
        {
            this.Buying_includes = new HashSet<Buying_includes>();
        }
    
        public int Order_number { get; set; }
        public Nullable<System.DateTime> Buying_Date { get; set; }
        public Nullable<System.DateTime> producing_Date { get; set; }
        public Nullable<int> expiry_count_days { get; set; }
        public string Warehouse_Name { get; set; }
        public Nullable<int> Supplier_D { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Buying_includes> Buying_includes { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
