//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ma5zeny
{
    using System;
    using System.Collections.Generic;
    
    public partial class Buying_includes
    {
        public int Amount { get; set; }
        public int Order_number { get; set; }
        public int BarCode { get; set; }
    
        public virtual Iteam Iteam { get; set; }
        public virtual Buying_Invoice Buying_Invoice { get; set; }
    }
}
