//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ma5zeny
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WarehouseEntities3 : DbContext
    {
        public WarehouseEntities3()
            : base("name=WarehouseEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Buying_includes> Buying_includes { get; set; }
        public virtual DbSet<Buying_Invoice> Buying_Invoice { get; set; }
        public virtual DbSet<Contains_Items> Contains_Items { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Iteam> Iteams { get; set; }
        public virtual DbSet<Iteam_Measuring_unit> Iteam_Measuring_unit { get; set; }
        public virtual DbSet<Manger> Mangers { get; set; }
        public virtual DbSet<Selling_includes> Selling_includes { get; set; }
        public virtual DbSet<Selling_Invoice> Selling_Invoice { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<Warehouse> Warehouses { get; set; }
    }
}
