//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ma5zeny
{
    using System;
    using System.Collections.Generic;
    
    public partial class transfer
    {
        public int transction_id { get; set; }
        public string from_warehouse { get; set; }
        public string to_warehouse { get; set; }
        public Nullable<int> item_barcode { get; set; }
        public Nullable<int> amount { get; set; }
        public Nullable<System.DateTime> Producing_Date { get; set; }
        public Nullable<System.DateTime> expiry_Date { get; set; }
    
        public virtual Iteam Iteam { get; set; }
        public virtual Warehouse Warehouse { get; set; }
        public virtual Warehouse Warehouse1 { get; set; }
    }
}
